### ISSUE TITLE
TypeScriptの導入(TypeScript)

### ISSUE THREAD

**Issue by kento-yoshidu** [kento-yoshidu/CSSAnimation-Tips#11]
## ToDo

- [x] TypeScriptのインストール
- [x] 各種ファイルのtsx化
- [x] `gatsby-config.js`のts化
- [x] `gatsby-node.js`のts化
- [x] `gatsby-browser.js`のts化
